CREATE TYPE status AS ENUM ('PENDING', 'COMPLETED');
CREATE TYPE priority AS ENUM ('NEUTRAL', 'LOW', 'MEDIUM', 'HIGH');
CREATE TYPE reminder_type AS ENUM ('UNTIL_DEADLINE', 'BEFORE_DEADLINE', 'DEADLINE_DAY', 'DIARY');
