ALTER TABLE task ALTER COLUMN priority TYPE TEXT;
DROP TYPE IF EXISTS priority;

ALTER TABLE task ALTER COLUMN status TYPE TEXT;
DROP TYPE IF EXISTS status;

ALTER TABLE task ALTER COLUMN reminder_type TYPE TEXT;
DROP TYPE IF EXISTS reminder_type;

