name: app
description: "TaskSave is a Flutter App for save your tasks and responsibilities"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localization: ^0.3.2
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  dio: ^5.0.0
  flutter_secure_storage: ^9.2.4
  jwt_decode: ^0.3.1
  provider: ^6.1.2
  mockito: ^5.4.5
  audioplayers: ^6.4.0
  email_validator: ^3.0.0
  shared_preferences: ^2.5.3
  app_links: ^6.4.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter_colorpicker: ^1.1.0
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/tasksave_logo_light.png
    - assets/images/tasksave_logo_dark.png
    - assets/images/confirm_email.png
    - assets/sounds/taskCompleted.mp3

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
